added other objects to is-elf-cu test

diff --git a/src/sh-scripts/test/Makefile.am b/src/sh-scripts/test/Makefile.am
--- a/src/sh-scripts/test/Makefile.am
+++ b/src/sh-scripts/test/Makefile.am
@@ -12,17 +12,23 @@ greet_LDADD     = libgreet.la
 
 
 libgreet_so_PATH = $(abs_builddir)/$(lt_obj_subdir)/libgreet.so
+libgreet_a_PATH = $(abs_builddir)/$(lt_obj_subdir)/libgreet.a
 
-.PHONY: libgreet_path
-libgreet_path: libgreet.la
-	@echo $(libgreet_so_PATH)
-	@test -x $(libgreet_so_PATH) && echo Y || echo N
+.PHONY: libgreet_paths
+libgreet_paths: libgreet.la
+	@echo -n '$(libgreet_so_PATH): '
+	@test -x $(libgreet_so_PATH) && echo 'found' || echo 'not found'
+	@echo -n '$(libgreet_a_PATH): '
+	@test -e $(libgreet_a_PATH) && echo 'found' || echo 'not found'
 
 
 check_SCRIPTS = test_is_elf_cu.sh
 TESTS         = $(check_SCRIPTS)
 CLEANFILES    = $(check_SCRIPTS)
 
-test_is_elf_cu.sh: ../is-elf-cu hello.o
-	echo '$^' > $@
+test_is_elf_cu.sh: ../is-elf-cu | hello.o howdy.o greet.o
+	echo '#! /usr/bin/env sh'          >  $@;  \
+	echo '../is-elf-cu hello.o &&  \\' >> $@;  \
+	echo '../is-elf-cu howdy.o &&  \\' >> $@;  \
+	echo '../is-elf-cu greet.o;'       >> $@
 	chmod +x $@
