fix stray # in cincludes

diff --git a/src/sh-scripts/cincludes b/src/sh-scripts/cincludes
--- a/src/sh-scripts/cincludes
+++ b/src/sh-scripts/cincludes
@@ -5,6 +5,10 @@
 #
 # ---------------------------------------------------------------------------- #
 
+set -eu;
+
+# ---------------------------------------------------------------------------- #
+
 as_me=cincludes;
 
 usage() {
@@ -23,14 +27,14 @@ lines which may conditionally include other files.
 
 # ---------------------------------------------------------------------------- #
 
+if test "$#" != 1; then
+  usage >&2;
+  exit 1;
+fi
+
 if test "$1" = "-h" || test "$1" = "--help"; then
   usage;
   exit 0;
-fi
-
-if test ${#} != 1; then
-  usage > /dev/stderr;
-  exit 1;
 fi
 
 
@@ -40,7 +44,7 @@ TARGET="$1";
 shift;
 
 if ! test -r "$TARGET"; then
-  echo "$as_me: Cannot read file: $TARGET" > /dev/stderr;
+  echo "$as_me: Cannot read file '$TARGET'" >&2;
   exit 1;
 fi
 
@@ -52,7 +56,7 @@ _joinlines() {
 }
 
 _matchpp() {
-  grep '^\s*\#\s*include\s*' < /dev/stdin;
+  grep '^\s*#\s*include\s*' < /dev/stdin;
 }
 
 _strippp() {
